- name: ChangeStation 
  aruco_id: 0
  x: 1.75
  y: -8.0
  yaw: -0.785
- name: Station2
  aruco_id: 2
  x: 4.2
  y: 2.0
  yaw: 0.0
- name: Station3
  aruco_id: 3
  x: 1.65
  y: 7.9
  yaw: 0.785
- name: Station4
  aruco_id: 4
  x: -3.7
  y: 8.2
  yaw: 0.785
